exports.settings = {
    "isWeb": false
}

exports.coins = {
    "sth": {
        ticker: "STH",
        title: "SmartHoldem",
        logo: "static/coins/sth.png",
        public: 0x3f,
        private: 0xff,
        generator: 'sthGenerator',
        downloadWallet: 'https://smartholdem.io/wallets',
        trade: "https://ex.xbts.io/market/XBTSX.STH_BTS",
        defi: "https://app.xbts.io/#/pools?a=sth",
        explorer: "https://blockexplorer.smartholdem.io",
        bip38: false,
        brainWallet: true,
        bip39: true
    },
    "zec": {
        ticker: "ZEC",
        title: "Zcash",
        logo: "static/coins/zec.png",
        bip44: 133,
        public: 7352,
        private: 128, //0x1cbd,
        scriptHash: 7357,
        bip32: {
            private: 0x0488ade4,
            public: 0x0488b21e
        },
        generator: 'btcGenerator',
        downloadWallet: 'https://z.cash/',
        explorer: "https://zecblockexplorer.com/",
        trade: "https://ex.xbts.io/market/XBTSX.ZEC_XBTSX.USDT",
        brainWallet: true,
        bip38: true,
        bip39: false
    },
    "kmd": {
        ticker: "KMD",
        title: "Komodo",
        logo: "static/coins/kmd.png",
        bip44: 141,
        public: 0x3c,
        private: 0xbc,
        generator: 'btcGenerator',
        downloadWallet: 'https://komodoplatform.com',
        explorer: "https://kmdexplorer.io",
        trade: "https://ex.xbts.io/market/XBTSX.KMD_XBTSX.USDT",
        brainWallet: true,
        bip38: true,
        bip39: false
    },
    "flux": {
        ticker: "FLUX",
        title: "Flux",
        logo: "static/coins/flux.png",
        bip44: 19167, // https://github.com/satoshilabs/slips/blob/master/slip-0044.md
        public: 7352,
        private: 128, //0x1cbd,
        scriptHash: 7357,
        bip32: {
            private: 0x0488ade4,
            public: 0x0488b21e
        },
        generator: 'btcGenerator',
        downloadWallet: 'https://runonflux.io/',
        explorer: "https://explorer.runonflux.io/",
        trade: "https://ex.xbts.io/market/XBTSX.FLUX_XBTSX.USDT",
        brainWallet: true,
        bip38: true,
        bip39: false
    },
    "eth": {
        ticker: "ETH",
        title: "Ethereum",
        logo: "static/coins/eth.png",
        public: null,
        private: null,
        generator: 'ethGenerator',
        downloadWallet: 'https://metamask.io/',
        trade: "https://ex.xbts.io/market/XBTSX.ETH_XBTSX.USDT",
        defi: "https://app.xbts.io/#/pools?a=eth",
        explorer: "https://etherscan.io/",
        bip38: false,
    },
    "etc": {
        ticker: "ETC",
        title: "Ethereum Classic",
        logo: "static/coins/etc.png",
        public: null,
        private: null,
        generator: 'ethGenerator',
        downloadWallet: 'https://metamask.io/',
        trade: "https://ex.xbts.io/market/XBTSX.ETC_XBTSX.USDT",
        defi: "https://app.xbts.io/#/pools?a=etc",
        explorer: "https://etherscan.io/",
        bip38: false,
    },
    "bsc": {
        ticker: "BNB",
        title: "BNB",
        logo: "static/coins/bnb.png",
        public: null,
        private: null,
        generator: 'ethGenerator',
        downloadWallet: 'https://metamask.io/',
        trade: "https://ex.xbts.io/market/XBTSX.BNB_BTS",
        explorer: "https://bscscan.com",
        bip38: false,
    },
    "btc": {
        ticker: "BTC",
        title: "Bitcoin",
        logo: "static/coins/btc.png",
        public: 0x0,
        private: 0x80,
        generator: 'btcGenerator',
        downloadWallet: 'https://bitcoin.org/en/choose-your-wallet',
        trade: "https://ex.xbts.io/market/XBTSX.BTC_XBTSX.USDT",
        defi: "https://app.xbts.io/#/pools?a=btc",
        explorer: "https://www.blockchain.com/explorer?view=btc",
        bip38: true,
        brainWallet: true,
    },
    "qtum": {
        ticker: "QTUM",
        title: "Qtum",
        logo: "static/coins/qtum.png",
        bip32: {
            private: 0x0488ade4,
            public: 0x0488b21e
        },
        bip44: 2301,
        public: 0x3A,
        private: 0x80,
        scripthash: 0x32,
        generator: 'btcGenerator',
        downloadWallet: 'https://qtum.org/',
        trade: "",
        defi: "",
        explorer: "https://qtum.info/",
        bip38: true,
        brainWallet: true,
    },
    "ltc": {
        ticker: "LTC",
        title: "Litecoin",
        logo: "static/coins/ltc.png",
        public: 0x30,
        private: 0xb0,
        generator: 'btcGenerator',
        downloadWallet: 'https://litecoin.org',
        trade: "https://ex.xbts.io/market/XBTSX.LTC_XBTSX.USDT",
        explorer: "https://chainz.cryptoid.info/ltc/",
        bip38: true,
        brainWallet: true,
    },
    "dash": {
        ticker: "DASH",
        title: "Dash",
        logo: "static/coins/dash.png",
        public: 0x4c,
        private: 0xcc,
        generator: 'btcGenerator',
        downloadWallet: 'https://www.dash.org/downloads/',
        trade: "https://ex.xbts.io/market/XBTSX.DASH_XBTSX.USDT",
        explorer: "https://chainz.cryptoid.info/dash/",
        bip38: true,
        brainWallet: true,
    },
    "doge": {
        ticker: "DOGE",
        title: "Dogecoin",
        logo: "static/coins/doge.png",
        public: 0x1e,
        private: 0x9e,
        generator: 'btcGenerator',
        downloadWallet: 'https://dogecoin.com/',
        trade: "https://ex.xbts.io/market/XBTSX.DOGE_BTS",
        explorer: "https://dogechain.info/",
        bip38: true,
        brainWallet: true,
    },
    "waves": {
        ticker: "WAVES",
        title: "WAVES",
        logo: "static/coins/waves.png",
        public: null,
        private: null,
        generator: 'wavesGenerator',
        downloadWallet: 'https://wavesplatform.com/products-wallet',
        trade: "https://ex.xbts.io/market/XBTSX.WAVES_XBTSX.USDT",
        explorer: "https://wavesexplorer.com/",
        bip38: false,
    },
    "rvn": {
        ticker: "RVN",
        title: "Ravencoin",
        logo: "static/coins/rvn.png",
        public: 0x3c,
        private: 0x80,
        generator: 'btcGenerator',
        downloadWallet: 'https://ravencoin.org/',
        defi: "https://app.xbts.io/#/pools?a=rvn",
        trade: "https://ex.xbts.io/market/XBTSX.RVN_XBTSX.USDT",
        explorer: "https://ravencoin.network",
        bip38: true,
        brainWallet: true,
    },
    "ppc": {
        ticker: "PPC",
        title: "Peercoin",
        public: 0x37,
        private: 0xb7,
        scripthash: 0xc4,
        generator: 'btcGenerator',
        downloadWallet: 'https://peercoin.net/wallet.html',
        trade: "https://ex.xbts.io/market/XBTSX.PPC_XBTSX.USDT",
        explorer: "https://chainz.cryptoid.info/ppc/",
        bip38: true,
        brainWallet: true,
    },
    "hvq": {
        ticker: "HVQ",
        title: "Hivecoin",
        public: 0x28,
        private: 0x70,
        generator: 'btcGenerator',
        downloadWallet: 'https://hivecoin.org',
        explorer: "https://explorer.hivecoin.org",
        bip38: true,
        brainWallet: true,
    },
    "vtc": {
        ticker: "VTC",
        title: "Vertcoin",
        public: 0x47,
        private: 0x80,
        generator: 'btcGenerator',
        downloadWallet: 'https://vertcoin.org/download-wallet',
        trade: "https://ex.xbts.io/market/XBTSX.VTC_XBTSX.USDT",
        explorer: "https://chainz.cryptoid.info/vtc",
        bip38: true,
        brainWallet: true,
    },
    "btg": {
        ticker: "BTG",
        title: "BitcoinGold",
        logo: "static/coins/btg.png",
        public: 0x26,
        private: 0x80,
        generator: 'btcGenerator',
        downloadWallet: 'https://bitcoingold.org/ecosystem/#wallets',
        trade: "https://ex.xbts.io/market/XBTSX.BTG_BTS",
        explorer: "https://btgexplorer.com",
        bip38: true,
        brainWallet: true,
    },
    "bch": {
        ticker: "BCH",
        title: "BitcoinCash",
        logo: "static/coins/bch.png",
        public: 0x0,
        private: 0x80,
        generator: 'bchGenerator',
        downloadWallet: 'https://www.bitcoincash.org/',
        trade: "https://ex.xbts.io/market/XBTSX.BCH_BTS",
        explorer: "https://btc.com/bch",
        bip38: false,
        brainWallet: false,
    },
    "dgb": {
        ticker: "DGB",
        title: "DigiByte",
        logo: "static/coins/dgb.png",
        bip44: 0x80000014,
        public: 0x1e,
        private: 0x9e,
        scripthash: 0x3f, // new 'S' prefix
        scripthash2: 0x05, // old '3' prefix
        generator: 'btcGenerator',
        downloadWallet: 'https://www.digibyte.io/digibyte-wallet-downloads',
        explorer: "https://chainz.cryptoid.info/dgb",
        bip38: false,
    },
    "onion": {
        ticker: "ONION",
        title: "DeepOnion",
        logo: "static/coins/onion.png",
        public: 0x1f,
        private: 0x9f,
        generator: 'btcGenerator',
        downloadWallet: 'https://github.com/deeponion/deeponion/releases',
        trade: "https://ex.xbts.io/market/XBTSX.ONION_BTS",
        explorer:"https://chainz.cryptoid.info/onion/",
        bip38: true,
        brainWallet: true,
    },
    "emc": {
        ticker: "EMC",
        title: "Emercoin",
        logo: "static/coins/emc.png",
        public: 0x21,
        private: 0x80,
        generator: 'btcGenerator',
        downloadWallet: 'http://emercoin.com/en/for-coinholders#download',
        trade: "https://ex.xbts.io/market/XBTSX.EMC_BTS",
        explorer:"https://explorer1.emercoin.com/",
        bip38: true,
        brainWallet: true,
    },
    "egc": {
        ticker: "EGC",
        title: "EverGreenCoin",
        logo: "static/coins/egc.png",
        public: 0x21,
        private: 0xa1,
        generator: 'btcGenerator',
        downloadWallet: 'https://evergreencoin.org',
        trade: "https://ex.xbts.io/market/XBTSX.EGC_BTS",
        explorer: "https://chainz.cryptoid.info/egc/",
        bip38: true,
        brainWallet: true,
    },
    "nmc": {
        ticker: "NMC",
        title: "NameCoin",
        logo: "static/coins/nmc.png",
        public: 0x34,
        private: 0x80,
        generator: 'btcGenerator',
        downloadWallet: 'https://namecoin.org/download/',
        trade: "https://ex.xbts.io/market/XBTSX.NMC_BTS",
        explorer: "https://chainz.cryptoid.info/nmc/",
        bip38: true,
        brainWallet: true,
    },
    "nvc": {
        ticker: "NVC",
        title: "Novacoin",
        logo: "static/coins/nvc.png",
        public: 0x08,
        private: 0x88,
        generator: 'btcGenerator',
        downloadWallet: 'https://sourceforge.net/projects/novacoin/files',
        trade: "https://ex.xbts.io/market/XBTSX.NVC_BTS",
        explorer: "https://explorer.novaco.in/",
        bip38: true,
        brainWallet: true,
    },
    "post": {
        ticker: "POST",
        title: "PostCoin",
        logo: "static/coins/post.png",
        public: 0x37,
        private: 0xb7,
        generator: 'btcGenerator',
        downloadWallet: 'https://postcoin.top/en/',
        trade: "https://ex.xbts.io/market/XBTSX.POST_BTS",
        explorer: "https://explorer.postcoin.top/",
        bip38: true,
        brainWallet: true,
    },
    "pivx": {
        ticker: "PIVX",
        title: "PIVX",
        logo: "static/coins/pivx.png",
        public: 0x1e,
        private: 0xd4,
        generator: 'btcGenerator',
        downloadWallet: 'https://pivx.org/wallet/',
        explorer: "https://chainz.cryptoid.info/pivx/",
        bip38: true,
        brainWallet: true,
    },
    /*
    "pot": {
        ticker: "POT",
        title: "Potcoin",
        logo: "static/coins/pot.png",
        public: 0x37,
        private: 0xb7,
        generator: 'btcGenerator',
        downloadWallet: 'https://www.potcoin.com/wallets',
        explorer: "https://chainz.cryptoid.info/pot/",
        bip38: true,
        brainWallet: true,
    },
     */
    "rdd": {
        ticker: "RDD",
        title: "ReddCoin",
        logo: "static/coins/rdd.png",
        public: 0x3d,
        private: 0xbd,
        scripthash: 0x05,
        generator: 'btcGenerator',
        downloadWallet: 'https://reddcoin.com/get-started',
        explorer: "https://rddblockexplorer.com/",
        bip38: true,
        brainWallet: true,
    },
    "rtm": {
        ticker: "RTM",
        title: "Raptoreum",
        logo: "static/coins/rtm.png",
        public: 0x3c,
        private: 0x80,
        scripthash: null,
        generator: 'btcGenerator',
        downloadWallet: 'https://raptoreum.com',
        explorer: "https://explorer.raptoreum.com",
        bip38: true,
        brainWallet: true,
    },
    "vrc": {
        ticker: "VRC",
        title: "Vericoin",
        logo: "static/coins/vrc.png",
        public: 0x46,
        private: 0x84,
        generator: 'btcGenerator',
        downloadWallet: 'https://vericoin.info/vericoin-digital-currency',
        explorer: "https://chainz.cryptoid.info/vrc/",
        bip38: true,
        brainWallet: true,
    },
    "bccx": {
        ticker: "BCCX",
        title: "BCCX",
        logo: "static/coins/bccx.png",
        public: 0x4b,
        private: 0xcb,
        generator: 'btcGenerator',
        downloadWallet: 'https://www.thebitconnectcoincommunity.com',
        trade: "https://ex.xbts.io/market/XBTSX.BCCX_BTS",
        explorer: "https://chainz.cryptoid.info/bccx/",
        bip38: true,
        brainWallet: true,
    },
    "xp": {
        ticker: "XP",
        title: "eXperience",
        logo: "static/coins/xp.png",
        public: 0x37,
        private: 0x49,
        generator: 'btcGenerator',
        downloadWallet: 'https://www.experiencepoints.io/downloads/',
        explorer: "https://chainz.cryptoid.info/xp/",
        bip38: false,
    },
    "guap": {
        ticker: "GUAP",
        title: "GuapCoin",
        logo: "static/coins/guap.png",
        public: 0x26,
        private: 0x2e,
        generator: 'btcGenerator',
        downloadWallet: 'http://www.guapcoin.org/',
        trade: "https://ex.xbts.io/market/XBTSX.GUAP_BTS",
        explorer: "https://guapexplorer.com/",
        bip38: true,
        brainWallet: true,
    },
    "trx": {
        ticker: "TRX",
        title: "Tron",
        logo: "static/coins/trx.png",
        public: 0x41,
        private: 0xc3,
        generator: 'trxGenerator',
        downloadWallet: 'https://tron.network/',
        trade: "https://ex.xbts.io/market/XBTSX.TRX_BTS",
        explorer: "https://tronscan.org",
        bip38: false,

    },
    "block": {
        ticker: "BLOCK",
        title: "Blocknet",
        logo: "static/coins/block.png",
        public: 0x1a,
        private: 0x9a,
        generator: 'btcGenerator',
        downloadWallet: 'https://blocknet.co',
        explorer: "https://chainz.cryptoid.info/block/",
        bip38: false,
    },
    /*
    "dem": {
        ticker: "DEM",
        title: "Deutsche eMark",
        logo: "static/coins/dem.png",
        public: 0x35,
        private: 0xb5,
        generator: 'btcGenerator',
        downloadWallet: 'https://github.com/emarkproject/eMark',
        bip38: true,
        brainWallet: true,
    },
     */
    "aur": {
        ticker: "AUR",
        title: "Aurora Coin",
        logo: "static/coins/aur.png",
        public: 23,
        private: 176,
        generator: 'btcGenerator',
        bip38: true,
        brainWallet: true,
        downloadWallet: 'https://github.com/aurarad/Auroracoin/releases',
        trade: "https://ex.xbts.io/market/XBTSX.AUR_XBTSX.USDT",
        defi: "",
        explorer: "https://chainz.cryptoid.info/aur/",
    },
    /*
    "prux": {
        title: "PRUX",
        logo: "static/coins/prux.png",
        public: 0x37,
        private: 0xb7,
        generator: 'btcGenerator',
        downloadWallet: 'https://prux.info/',
    },
    "nobt": {
        title: "NobtCoin",
        logo: "static/coins/nobt.png",
        public: 0xf,
        private: 0x55,
        generator: 'btcGenerator',
        downloadWallet: 'https://github.com/nobtcoin/Nobtcoin/releases',
    },
     */
    /*
   "steep": {
       title: "SteepCoin",
       logo: "static/coins/steep.png",
       public: 0x7d,
       private: 0xfd,
       generator: 'btcGenerator',
       downloadWallet: 'https://steepcoin.org/en',
   },
    */
    /*
   "lsk": {
       title: "Lisk",
       logo: "static/coins/lisk.png",
       public: null,
       private: null,
       generator: 'liskGenerator',
       downloadWallet: 'https://lisk.io',
   },
    */
    /*
    "ark": {
        title: "Ark",
        logo: "static/coins/ark.png",
        public: 0x17,
        private: 0xaa,
        generator: 'sthGenerator',
        downloadWallet: 'https://ark.io/wallet',
        explorer: "https://explorer.ark.io",
        bip38: false,
        bip39: true
    },
     */
}

exports.templates = {
    "ru": [
        "1 - Космос",
        "2 - Пицца",
        "3 - Новый год, Рождество",
        "4 - Новый год",
        "5 - Красный конверт",
        "6 - Белый Стиль",
        "7 - Неон",
        "8 - Китай",
        "9 - Кошки",
        "10 - Собаки",
        "11 - Любовь",
        "12 - Молния",
        "13 - Розы",
        "14 - НЛО",
        "15 - Лунный Новый Год",
        "16 - Камуфляж",
        "17 - Одуванчик",
        "18 - Океан",
        "19 - Медитация",
        "20 - Черный Стиль",
        "21 - Я тебя люблю",
        "22 - Пастель",
        "23 - Новый год 2",
        "24 - Точки",
        "25 - Пасха",
        "26- Камуфляж 2",
        "27 - Единорог",
        "28 - Цветы",
        "29 - Круги",
        "30 - Пионы",
        "31 - Пальмы",
        "32 - Зеленый Стиль",
        "33 - Свадьба",
        "34 - Солнце",
        "35 - Пурпурный Стиль",
        "36 - Абстракция",
        "37 - Неон 2",
        "38 - Торговля"
    ],
    en: [
        "1 - Space",
        "2 - Pizza",
        "3 - New Year, Christmas",
        "4 - Новый год",
        "5 - Red envelope",
        "6 - White Style",
        "7 - Neon",
        "8 - China",
        "9 - Cats",
        "10 - Dogs",
        "11 - Love",
        "12 - Lightning",
        "13 - Roses",
        "14 - UFO",
        "15 - Lunar New Year",
        "16 - Camouflage",
        "17 - Dandelion",
        "18 - Ocean",
        "19 - Meditation",
        "20 - Black Style",
        "21 - I love you",
        "22 - Pastel",
        "23 - New Year 2",
        "24 - Dots",
        "25 - Easter",
        "26- Camouflage 2",
        "27 - Unicorn",
        "28 - Flowers",
        "29 - Circles",
        "30 - Peonies",
        "31 - Palms",
        "32 - Green Style",
        "33 - Wedding",
        "34 - Sun",
        "35 - Purple Style",
        "36 - Abstraction",
        "37 - Neon 2",
        "38 - Trading"
    ]
}

exports.info = {
    "ZEC": {
        "title": "",
        "text": "Zcash was the first project to implement zk-SNARKs, a novel form of zero-knowledge cryptography that gives its users the strongest privacy available in any digital currency.",
    },
    "STH": {
        "title": "Decentralized gaming platform",
        "text": "STH is a native coin of the Decentralized platform SmartHoldem https://smartholdem.io.\r\n" +
            "STH use in DApps, Rewarder, GM SmartNote, Money Tree, ANTiBounty Twitter Promo Service, DexGame \"Heads or Tails\" & Decentralized SmartHoldem Blockchain Poker Room.\r\n\r\n" +
            "SmartHoldem Coin [STH] is a core asset of the XBTS Cross-Chain Dex https://ex.xbts.io/asset/XBTSX.STH.\r\n\r\n" +
            "STH has many options for use: for paying fees for transactions on the XBTS exchange, SmartHOLDER Staking & DeFi AMMob liquidity pools..\n"
    },
    "LSK": {
        "title": "",
        "text": ""
    },
    "ARK": {
        "title": "",
        "text": ""
    },
    "POST": {
        "title": "PostCoin",
        "text": "Postcoin Internet currency which provides safe payments to any place of the world. Business, investment and settlement friendly services in the Internet and around the world."
    },
    "DOGE": {
        "title": "DogeCoin",
        "text": "Based on the popular \"Doge\" Internet meme and featuring a Shiba Inu on its logo, Dogecoin (DOGE) is a cryptocurrency that was forked from Litecoin in Dec 2013. Dogecoin has been used primarily as a tipping system on Reddit and Twitter to reward the creation or sharing of quality content. Dogecoin was created by Billy Markus from Portland, Oregon and Jackson Palmer from Sydney, Australia. Both had envisaged Dogecoin as a fun, light-hearted cryptocurrency that would have greater appeal beyond the core Bitcoin audience.",
    },
    "BTC": {
        "title": "Bitcoin",
        "text": "Bitcoin (BTC) is a consensus network that enables a new payment system and a completely digital currency. Powered by its users, it is a peer to peer payment network that requires no central authority to operate. On October 31st, 2008, an individual or group of individuals operating under the pseudonym \"Satoshi Nakamoto\" published the Bitcoin Whitepaper and described it as: \"a purely peer-to-peer version of electronic cash, which would allow online payments to be sent directly from one party to another without going through a financial institution.",
    },
    "BCH": {
        "title": "",
        "text": "Bitcoin Cash (BCH) is hard fork (a community-activated update to the protocol or code) of Bitcoin that took effect on August 1st, 2017 that increased the block size to 8MB, to help the scale the underlying technology of Bitcoin.Nov 16th 2018: BCH was hard forked again and split into Bitcoin SV and Bitcoin ABC. Bitcoin ABC became the dominant chain and took over the BCH ticker as it had more hashpower and majority of the nodes in the network.",
    },
    "LTC": {
        "title": "Litecoin",
        "text": "Litecoin is a peer-to-peer cryptocurrency created by Charlie Lee. It was created based on the Bitcoin protocol but differs in terms of the hashing algorithm used. Litecoin uses the memory intensive Scrypt proof of work mining algorithm. Scrypt allows consumer-grade hardware such as GPU to mine those coins.",
    },
    "DASH": {
        "title": "DASH Coin",
        "text": "Dash (DASH) describes itself as digital cash that aims to offer financial freedom to everyone. Payments are fast, easy, secure, and with near-zero fees. Built to support real-life use cases, Dash aims to provide a fully-decentralized payments solution. Users can purchase goods at thousands of merchants and trade it at major exchanges and brokers around the globe.",
    },
    "BTG": {
        "title": "Bitcoin GOLD",
        "text": "Bitcoin Gold (BTG) is a fork of Bitcoin that occurred on October 24, 2017 on block 419406. Bitcoin Gold changed Bitcoin’s proof-of-work algorithm from SHA256 to Equihash rendering specialised mining equipment obsolete in an attempt to democratise the Bitcoin mining process.",
    },
    "NVC": {
        "title": "Novacoin",
        "text": "Novacoin (NVC) is a cryptocurrency. Users are able to generate NVC through the process of mining.",
    },
    "42": {
        "title": "42-Coin",
        "text": "42-coin (42) is a cryptocurrency. Users are able to generate 42 through the process of mining. 42-coin has a current supply of 42.",
    },
    "NMC": {
        "title": "Namecoin",
        "text": "Namecoin is an experimental open-source technology which improves decentralization, security, censorship resistance, privacy, and speed of certain components of the Internet infrastructure such as DNS and identities.\n" +
            "\n" +
            "(For the technically minded, Namecoin is a key/value pair registration and transfer system based on the Bitcoin technology.)\n" +
            "\n" +
            "Bitcoin frees money – Namecoin frees DNS, identities, and other technologies.",
    },
    "WAVES": {
        "title": "Platform",
        "text": "Open blockchain platform and development toolset for Web 3.0 applications and decentralized solutions. Waves Platform’s mission lies in creating an ecosystem that aims to accelerate the shift from centralized to decentralized systems and an emphasis on the individual’s control of their own funds and assets, personal data, and privacy. Waves Platform describes itself as an open network for Web 3.0 applications and custom decentralized solutions, with a range of purpose-designed tools for making the process of developing and running dApps easy and accessible. Launched in 2016, Waves has since released several blockchain-based solutions. Waves’ technology is designed to address the needs of developers and companies that want to leverage the properties of blockchain systems – including their security, auditability, verifiability and the trustless execution of transactions and business logic.",
    },
    "ONION": {
        "price": "DeepOnion",
        "text": "DeepOnion is a privacy cryptocurrency that uses the anonymous Tor® network by default to protect the identity of users. Not a single IP address was leaked since the wallet launched. DeepSend is currently being tested on mainnet for untraceable blockchain transactions.",
    },
    "EGC": {
        "title": "EverGreenCoin",
        "text": "EverGreenCoin (EGC) is a cryptocurrency. Users are able to generate EGC through the process of mining.",
    },
    "VRC": {
        "title": "VeriCoin",
        "text": "VeriCoin is a purely digital currency that runs on its own protocol, PoST (Proof-of-Stake-Time), which is unique to VeriCoin.",
    },
    "VRM": {
        "title": "VeriumReserve Coin",
        "text": "Current digital currencies face an impossible task of trying to be both a fast currency and a secure store of value. VeriCoin and Verium together solve this problem with the groundbreaking dual blockchain system called Binary-Chain. Binary-Chain, secures and accelerates transactions by leveraging complementary protocol technologies (PoST [Proof-of-Stake-Time] and PoWT [Proof-of-Work-Time]), into a cutting edge blockchain ecosystem.",
    },
    "ETH": {
        "title": "",
        "text": "Ethereum is a decentralized platform for applications. Applications build on it can use smart contracts - computer algorithms which execute themselves when data is supplied to the platform. There is no need for any human operators.",
    },
    "MDL": {
        "title": "Talent Hub",
        "text": "MDL Talent Hub is the ecosystem designed to facilitate the talent sourcing market. Insightful expertise in both IT technologies and the entertainment industry allows us to bring the most efficient and effective medium for collaboration between artists, bookers, and brands.",
    },
    "SKY": {
        "title": "Skycoin",
        "text": "Skycoin is a currency for digital bandwidth, backed by the new internet. Fast transactions, no transaction fees, Skycoin is a third-generation cryptocurrency supporting a new free and open internet.\n" +
            "\n" +
            "Skycoin [SKY] is a cryptocurrency with its own blockchain. ",
        "git": "https://github.com/skycoin"
    },
    "SLB": {
        "title": "Solar Bankers Coin",
        "text": "Peer-to-peer energy trading solution and distributed data storage network.\n" +
            "\n" +
            "Solar Bankers Coin [SLB] is a cryptocurrency with its own blockchain.",
    },
    "GRS": {
        "title": "Groestlcoin",
        "text": "Groestlcoin (GRS) is a cryptocoin, that is optionally private. Anyone can mine it effectively, with GPU.",
    },
    "BCCX": {
        "title": "BlockChainCoinX",
        "text": "BlockChainCoinX (BCCX) is an open source, blockchain based, decentralized cryptocurrency that enables instant payments to anyone with minimum transaction fees. BlockChainCoinX also allows you to earn interest for helping maintain security on the network by holding BCCX in a Qt Desktop wallet that is attached to the network and allowing transactions to flow through it.",
    },
    "GUAP": {
        "title": "Guapcoin",
        "text": "A Global Financial Identity for the African Diaspora\n" +
            "With a core mission is to repair, enhance, and strengthen the core value systems\n" +
            "of Black & Brown people throughout the African diaspora using cryptocurrency. A decentralized digital coin can be traded between peers instantly.\n" +
            "Guap Coin is fast, secure, and highly scalable. Guap is for everybody but our primary mission is to uplift those economic communities that have been left out of the cryptocurrency revolution.",
    },
    "RVN": {
        "title": "Ravencoin",
        "text": "Ravencoin is a digital peer to peer network that aims to implement a use case specific blockchain, designed to efficiently handle one specific function: the transfer of assets from one party to another. Built on a fork of the Bitcoin code, Ravencoin was launched January 3rd, 2018, and is a truly open source project (no ICO or masternodes). It focuses on building a useful technology, with a strong and growing community.",
    },
}
